-- cp2-4.hs: O(n^2) counter-pump (2-register Minsky). n=4
-- Start: (0, 1, 0). Goal: (0, 1, 1).
-- Generated by make-cp2.py.

-- Phase 1 (pc=2..5): x := 4
-- Phase 2 (pc=6): outer loop, while x>0 do 4 INC y + DEC x
-- Phase 3 (pc=12): drain y from 16 to 0
-- HALT   (pc=13): noop to pc=1

cp2 :: (Int, Int, Int) -> (Int, Int, Int)

-- Phase 0: y := 0 (hs2maze starts at y=1)
cp2 (x, 0,    0) = cp2 (  x,   0,    2)
cp2 (x, y,    0) = cp2 (  x, y-1,    2)

-- Phase 1: x := 4
cp2 (x, y,    2) = cp2 (x+1,   y,    3)
cp2 (x, y,    3) = cp2 (x+1,   y,    4)
cp2 (x, y,    4) = cp2 (x+1,   y,    5)
cp2 (x, y,    5) = cp2 (x+1,   y,    6)

-- Phase 2 outer (pc=6): zero-branch goes to drain, else noop
cp2 (0, y,    6) = cp2 (  0,   y,   12)
cp2 (x, y,    6) = cp2 (  x,   y,    7)

-- Phase 2 inner: 4 INC y
cp2 (x, y,    7) = cp2 (  x, y+1,    8)
cp2 (x, y,    8) = cp2 (  x, y+1,    9)
cp2 (x, y,    9) = cp2 (  x, y+1,   10)
cp2 (x, y,   10) = cp2 (  x, y+1,   11)

-- Phase 2 DEC x (pc=11)
cp2 (x, y,   11) = cp2 (x-1,   y,    6)

-- Phase 3 drain y (pc=12)
cp2 (x, 0,   12) = cp2 (  x,   0,   13)
cp2 (x, y,   12) = cp2 (  x, y-1,   12)

-- HALT (pc=13): noop to pc=1
cp2 (x, y,   13) = cp2 (  x,   y,    1)
