-- cp2-4.hs: O(n^2) counter-pump (2-register Minsky). n=4
-- Start: (0, 1, 0). Goal: (0, 0, 1).
-- Generated by make-cp2.py.

-- Phase 1 (pc=2..5): x := 4
-- Phase 2 (pc=7): outer loop, while x>0 do 4 INC y + DEC x
-- Phase 3 (pc=14): drain y from 16 to 0
-- HALT   (pc=15): noop to pc=1

cp2 :: (Int, Int, Int) -> (Int, Int, Int)

-- Phase 0: y := 0 (hs2maze starts at y=1)
cp2 (x, 0,    0) = cp2 (  x,   0,    2)
cp2 (x, y,    0) = cp2 (  x, y-1,    2)

-- Phase 1: x := 4
cp2 (x, y,    2) = cp2 (x+1,   y,    3)
cp2 (x, y,    3) = cp2 (x+1,   y,    4)
cp2 (x, y,    4) = cp2 (x+1,   y,    5)
cp2 (x, y,    5) = cp2 (x+1,   y,    6)

-- Forwarder pc=6: Phase 1 → outer entry (intra, no edge sharing)
cp2 (x, y,    6) = cp2 (  x,   y,    7)

-- Phase 2 outer (pc=7): zero-branch goes to drain, else noop
cp2 (0, y,    7) = cp2 (  0,   y,   14)
cp2 (x, y,    7) = cp2 (  x,   y,    8)

-- Phase 2 inner: 4 INC y
cp2 (x, y,    8) = cp2 (  x, y+1,    9)
cp2 (x, y,    9) = cp2 (  x, y+1,   10)
cp2 (x, y,   10) = cp2 (  x, y+1,   11)
cp2 (x, y,   11) = cp2 (  x, y+1,   12)

-- Phase 2 DEC x (pc=12)
cp2 (x, y,   12) = cp2 (x-1,   y,   13)

-- Forwarder pc=13: Phase 2 DEC x → outer entry (intra)
cp2 (x, y,   13) = cp2 (  x,   y,    7)

-- Phase 3 drain y (pc=14)
cp2 (x, 0,   14) = cp2 (  x,   0,   15)
cp2 (x, y,   14) = cp2 (  x, y-1,   14)

-- HALT (pc=15): bare-tuple base case for pc=1, no recursive call
cp2 (x, y,   15) = (  x,   y,    1)
