-- cp2-6.hs: O(n^2) counter-pump (2-register Minsky). n=6
-- Start: (0, 1, 0). Goal: (0, 0, 1).
-- Generated by make-cp2.py.

-- Phase 1 (pc=2..7): x := 6
-- Phase 2 (pc=8): outer loop, while x>0 do 6 INC y + DEC x
-- Phase 3 (pc=16): drain y from 36 to 0
-- HALT   (pc=17): noop to pc=1

cp2 :: (Int, Int, Int) -> (Int, Int, Int)

-- Phase 0: y := 0 (hs2maze starts at y=1)
cp2 (x, 0,    0) = cp2 (  x,   0,    2)
cp2 (x, y,    0) = cp2 (  x, y-1,    2)

-- Phase 1: x := 6
cp2 (x, y,    2) = cp2 (x+1,   y,    3)
cp2 (x, y,    3) = cp2 (x+1,   y,    4)
cp2 (x, y,    4) = cp2 (x+1,   y,    5)
cp2 (x, y,    5) = cp2 (x+1,   y,    6)
cp2 (x, y,    6) = cp2 (x+1,   y,    7)
cp2 (x, y,    7) = cp2 (x+1,   y,    8)

-- Phase 2 outer (pc=8): zero-branch goes to drain, else noop
cp2 (0, y,    8) = cp2 (  0,   y,   16)
cp2 (x, y,    8) = cp2 (  x,   y,    9)

-- Phase 2 inner: 6 INC y
cp2 (x, y,    9) = cp2 (  x, y+1,   10)
cp2 (x, y,   10) = cp2 (  x, y+1,   11)
cp2 (x, y,   11) = cp2 (  x, y+1,   12)
cp2 (x, y,   12) = cp2 (  x, y+1,   13)
cp2 (x, y,   13) = cp2 (  x, y+1,   14)
cp2 (x, y,   14) = cp2 (  x, y+1,   15)

-- Phase 2 DEC x (pc=15)
cp2 (x, y,   15) = cp2 (x-1,   y,    8)

-- Phase 3 drain y (pc=16)
cp2 (x, 0,   16) = cp2 (  x,   0,   17)
cp2 (x, y,   16) = cp2 (  x, y-1,   16)

-- HALT (pc=17): bare-tuple base case for pc=1, no recursive call
cp2 (x, y,   17) = (  x,   y,    1)
