#!/usr/bin/env python3
"""make-cp2.py — Generate cp2-N.hs, a 2-register O(n^2) counter-pump Minsky.

The machine starts at (0, 1, 0) and halts at (0, 1, 1).  It sets x := n,
then iterates while x > 0 doing n INC y followed by one DEC x, so y ends
up at n*n.  Phase 3 drains y back to 0 via ny, and the final noop drops
the walker at pc=1 (the hs2maze goal).

Usage: python3 make-cp2.py N [--test] > cp2-N.hs

With --test, an extra witness register `o` is appended (3 registers + pc = 4 slots).
`o` is incremented once per inner INC y step, so HALT state has o = n^2.
"""
import sys

VERSION = "1.2"

USAGE = """\
Usage: make-cp2.py N [--test]
       make-cp2.py --help | -h
       make-cp2.py --version | -V

Generate cp2-N.hs, a 2-register Minsky-style O(n^2) counter-pump Haskell
source.  The output is a tail-recursive `cp2 :: (Int, Int, Int) -> ...`
definition with state slots (x, y, pc), starting at (0, 1, 0) and halting
at (0, 1, 1).  Pipe stdout into a file and feed it to hs2maze.py to turn
it into a repeated-maze string.

Internally the machine runs: y := 0; x := N; while x > 0 do (INC y) N
times then DEC x; finally drain y back to 0 and noop into pc=1.  Total
INC y count is N^2, which is what gives the maze its O(n^2) length.

Positional argument:
  N             counter-pump size (N >= 1).  The walker fires INC y
                exactly N^2 times before HALT.

Options:
  --test        emit a self-contained runnable Haskell with an extra
                witness register o.  The HALT rule returns a bare
                tuple, and a `main :: IO ()` prints the final state.
                Run via `runghc FILE.hs`; output is `(0,1,N^2,1)` on a
                single line, confirming o = N^2.
  -h, --help    show this message and exit.
  -V, --version show the script version (currently v{version}) and exit.
""".format(version=VERSION)


def make(n, test=False):
    pc = 2
    p1 = list(range(pc, pc + n)); pc += n
    p_outer = pc; pc += 1
    p_inner = list(range(pc, pc + n)); pc += n
    p_decx = pc; pc += 1
    p_drain = pc; pc += 1
    halt_pc = pc; pc += 1

    if test:
        # 4-slot form: (x, y, o, pc).  `o` is the counting witness register.
        sig = "cp2 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)"
        start = "(0, 1, 0, 0)"
        goal = f"(0, 0, {n*n}, 1)"
    else:
        sig = "cp2 :: (Int, Int, Int) -> (Int, Int, Int)"
        start = "(0, 1, 0)"
        goal = "(0, 0, 1)"

    def rule(lhs_slots, rhs_slots, pc_lhs, pc_rhs, inc_o=False, halt=False):
        """Format one cp2 rule; pads `o` slot when test=True (incremented if inc_o).
        If halt=True, emit RHS as a bare tuple (no `cp2` prefix) so that the
        equation is a true Haskell base case usable directly under runghc.
        In test mode the recursive RHS goes through `cp2_`, the trace wrapper
        defined later in the file, so every step is logged via Debug.Trace."""
        if test:
            o_rhs = "o+1" if inc_o else "  o"
            lhs = ", ".join(lhs_slots + ["o"])
            rhs = ", ".join(rhs_slots + [o_rhs])
        else:
            lhs = ", ".join(lhs_slots)
            rhs = ", ".join(rhs_slots)
        if halt:
            rhs_prefix = ""
        elif test:
            rhs_prefix = "cp2_ "
        else:
            rhs_prefix = "cp2 "
        return f"cp2 ({lhs}, {pc_lhs:4d}) = {rhs_prefix}({rhs}, {pc_rhs:4d})"

    out = []
    out += [
        f"-- cp2-{n}.hs: O(n^2) counter-pump (2-register Minsky). n={n}",
        f"-- Start: {start}. Goal: {goal}.",
        f"-- Generated by make-cp2.py" + (" --test" if test else "") + ".",
    ]
    if test:
        out.append(f"-- Test mode: register o counts inner INC y firings; expect o = n^2 = {n*n}.")
    out += [
        "",
        f"-- Phase 1 (pc={p1[0]}..{p1[-1]}): x := {n}",
        f"-- Phase 2 (pc={p_outer}): outer loop, while x>0 do {n} INC y + DEC x",
        f"-- Phase 3 (pc={p_drain}): drain y from {n*n} to 0",
        f"-- HALT   (pc={halt_pc}): noop to pc=1",
        "",
    ]
    if test:
        out += ["import Debug.Trace (trace)", ""]
    out += [
        sig,
        "",
        f"-- Phase 0: y := 0 (hs2maze starts at y=1)",
        rule(["x", "0"], ["  x", "  0"], 0, p1[0]),
        rule(["x", "y"], ["  x", "y-1"], 0, p1[0]),
        "",
        f"-- Phase 1: x := {n}",
    ]
    for i, pc_i in enumerate(p1):
        nxt = p1[i + 1] if i + 1 < n else p_outer
        out.append(rule(["x", "y"], ["x+1", "  y"], pc_i, nxt))
    out += [
        "",
        f"-- Phase 2 outer (pc={p_outer}): zero-branch goes to drain, else noop",
        rule(["0", "y"], ["  0", "  y"], p_outer, p_drain),
        rule(["x", "y"], ["  x", "  y"], p_outer, p_inner[0]),
        "",
        f"-- Phase 2 inner: {n} INC y" + (" (each also INC o)" if test else ""),
    ]
    for i, pc_i in enumerate(p_inner):
        nxt = p_inner[i + 1] if i + 1 < n else p_decx
        out.append(rule(["x", "y"], ["  x", "y+1"], pc_i, nxt, inc_o=True))
    out += [
        "",
        f"-- Phase 2 DEC x (pc={p_decx})",
        rule(["x", "y"], ["x-1", "  y"], p_decx, p_outer),
        "",
        f"-- Phase 3 drain y (pc={p_drain})",
        rule(["x", "0"], ["  x", "  0"], p_drain, halt_pc),
        rule(["x", "y"], ["  x", "y-1"], p_drain, p_drain),
        "",
        f"-- HALT (pc={halt_pc}): bare-tuple base case for pc=1, no recursive call",
        rule(["x", "y"], ["  x", "  y"], halt_pc, 1, halt=True),
    ]
    if test:
        out += [
            "",
            "-- cp2_ : trace wrapper.  Every recursive RHS goes through cp2_ so",
            "-- Debug.Trace.trace prints each intermediate state to stderr.",
            "cp2_ :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)",
            "cp2_ args = trace (show args) (cp2 args)",
            "",
            f"-- main: trace every step from {start}, then print the final state.",
            f"-- Expected final state: {goal}.",
            "main :: IO ()",
            f"main = print (cp2_ {start})",
        ]
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    if any(a in ("-h", "--help") for a in args):
        print(USAGE, end="")
        return
    if any(a in ("-V", "--version") for a in args):
        print(f"make-cp2.py v{VERSION}")
        return
    test = False
    if "--test" in args:
        test = True
        args.remove("--test")
    if len(args) != 1:
        print(USAGE, end="", file=sys.stderr)
        sys.exit(1)
    try:
        n = int(args[0])
    except ValueError:
        print(f"N must be an integer (got {args[0]!r})", file=sys.stderr)
        sys.exit(1)
    if n < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(n, test=test), end='')


if __name__ == '__main__':
    main()
