#!/usr/bin/env python3
"""make-cp2.py — Generate cp2-N.hs, a 2-register O(n^2) counter-pump Minsky.

The machine starts at (0, 1, 0) and halts at (0, 1, 1).  It sets x := n,
then iterates while x > 0 doing n INC y followed by one DEC x, so y ends
up at n*n.  Phase 3 drains y back to 0 via ny, and the final noop drops
the walker at pc=1 (the hs2maze goal).

Usage: python3 make-cp2.py N > cp2-N.hs
"""
import sys

VERSION = "1.0"

USAGE = """\
Usage: make-cp2.py N
       make-cp2.py --help | -h
       make-cp2.py --version | -V

Generate cp2-N.hs, a 2-register Minsky-style O(n^2) counter-pump Haskell
source.  The output is a tail-recursive `cp2 :: (Int, Int, Int) -> ...`
definition with state slots (x, y, pc), starting at (0, 1, 0) and halting
at (0, 1, 1).  Pipe stdout into a file and feed it to hs2maze.py to turn
it into a repeated-maze string.

Internally the machine runs: y := 0; x := N; while x > 0 do (INC y) N
times then DEC x; finally drain y back to 0 and noop into pc=1.  Total
INC y count is N^2, which is what gives the maze its O(n^2) length.

Positional argument:
  N             counter-pump size (N >= 1).  The walker fires INC y
                exactly N^2 times before HALT.

Options:
  -h, --help    show this message and exit.
  -V, --version show the script version (currently v{version}) and exit.
""".format(version=VERSION)


def make(n):
    pc = 2
    p1 = list(range(pc, pc + n)); pc += n
    p_outer = pc; pc += 1
    p_inner = list(range(pc, pc + n)); pc += n
    p_decx = pc; pc += 1
    p_drain = pc; pc += 1
    halt_pc = pc; pc += 1

    out = []
    out += [
        f"-- cp2-{n}.hs: O(n^2) counter-pump (2-register Minsky). n={n}",
        f"-- Start: (0, 1, 0). Goal: (0, 1, 1).",
        f"-- Generated by make-cp2.py.",
        "",
        f"-- Phase 1 (pc={p1[0]}..{p1[-1]}): x := {n}",
        f"-- Phase 2 (pc={p_outer}): outer loop, while x>0 do {n} INC y + DEC x",
        f"-- Phase 3 (pc={p_drain}): drain y from {n*n} to 0",
        f"-- HALT   (pc={halt_pc}): noop to pc=1",
        "",
        "cp2 :: (Int, Int, Int) -> (Int, Int, Int)",
        "",
        f"-- Phase 0: y := 0 (hs2maze starts at y=1)",
        f"cp2 (x, 0,    0) = cp2 (  x,   0, {p1[0]:4d})",
        f"cp2 (x, y,    0) = cp2 (  x, y-1, {p1[0]:4d})",
        "",
        f"-- Phase 1: x := {n}",
    ]
    for i, pc_i in enumerate(p1):
        nxt = p1[i + 1] if i + 1 < n else p_outer
        out.append(f"cp2 (x, y, {pc_i:4d}) = cp2 (x+1,   y, {nxt:4d})")
    out += [
        "",
        f"-- Phase 2 outer (pc={p_outer}): zero-branch goes to drain, else noop",
        f"cp2 (0, y, {p_outer:4d}) = cp2 (  0,   y, {p_drain:4d})",
        f"cp2 (x, y, {p_outer:4d}) = cp2 (  x,   y, {p_inner[0]:4d})",
        "",
        f"-- Phase 2 inner: {n} INC y",
    ]
    for i, pc_i in enumerate(p_inner):
        nxt = p_inner[i + 1] if i + 1 < n else p_decx
        out.append(f"cp2 (x, y, {pc_i:4d}) = cp2 (  x, y+1, {nxt:4d})")
    out += [
        "",
        f"-- Phase 2 DEC x (pc={p_decx})",
        f"cp2 (x, y, {p_decx:4d}) = cp2 (x-1,   y, {p_outer:4d})",
        "",
        f"-- Phase 3 drain y (pc={p_drain})",
        f"cp2 (x, 0, {p_drain:4d}) = cp2 (  x,   0, {halt_pc:4d})",
        f"cp2 (x, y, {p_drain:4d}) = cp2 (  x, y-1, {p_drain:4d})",
        "",
        f"-- HALT (pc={halt_pc}): noop to pc=1",
        f"cp2 (x, y, {halt_pc:4d}) = cp2 (  x,   y,    1)",
    ]
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    if any(a in ("-h", "--help") for a in args):
        print(USAGE, end="")
        return
    if any(a in ("-V", "--version") for a in args):
        print(f"make-cp2.py v{VERSION}")
        return
    if len(args) != 1:
        print(USAGE, end="", file=sys.stderr)
        sys.exit(1)
    try:
        n = int(args[0])
    except ValueError:
        print(f"N must be an integer (got {args[0]!r})", file=sys.stderr)
        sys.exit(1)
    if n < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(n), end='')


if __name__ == '__main__':
    main()
