-- cp3-3-3d.hs: O(n^3) counter-pump (3-register Minsky). n=3
-- Start: (0, 1, 0, 0). Goal: (0, 0, 0, 1).
-- Generated by make-cp3.py.  Feed through nd-to-2d.py → hs2maze.py.

-- Outer  (pc=5): x=0 → halt, else y := 3, goto middle.
-- Middle (pc=9): y=0 → DEC x, goto outer, else z := 3, goto inner.
-- Inner  (pc=13): z=0 → DEC y, goto middle, else DEC z self-loop.

cp3 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)

-- Phase 0: y := 0
cp3 (x, y, z,    0) = cp3 (  x, y-1,   z,    2)

-- Phase 1: x := 3
cp3 (x, y, z,    2) = cp3 (x+1,   y,   z,    3)
cp3 (x, y, z,    3) = cp3 (x+1,   y,   z,    4)
cp3 (x, y, z,    4) = cp3 (x+1,   y,   z,    5)

-- Outer entry (pc=5)
cp3 (0, y, z,    5) = cp3 (  0,   y,   z,   14)
cp3 (x, y, z,    5) = cp3 (  x,   y,   z,    6)

-- Outer INC y chain (y := 3)
cp3 (x, y, z,    6) = cp3 (  x, y+1,   z,    7)
cp3 (x, y, z,    7) = cp3 (  x, y+1,   z,    8)
cp3 (x, y, z,    8) = cp3 (  x, y+1,   z,    9)

-- Middle entry (pc=9)
cp3 (x, 0, z,    9) = cp3 (x-1,   0,   z,    5)
cp3 (x, y, z,    9) = cp3 (  x,   y,   z,   10)

-- Middle INC z chain (z := 3)
cp3 (x, y, z,   10) = cp3 (  x,   y, z+1,   11)
cp3 (x, y, z,   11) = cp3 (  x,   y, z+1,   12)
cp3 (x, y, z,   12) = cp3 (  x,   y, z+1,   13)

-- Inner (pc=13)
cp3 (x, y, 0,   13) = cp3 (  x, y-1,   0,    9)
cp3 (x, y, z,   13) = cp3 (  x,   y, z-1,   13)

-- HALT (pc=14): bare-tuple base case for pc=1, no recursive call
cp3 (x, y, z,   14) = (  x,   y,   z,    1)
