-- cp3-2-3d.hs: O(n^3) counter-pump (3-register Minsky). n=2
-- Start: (0, 1, 0, 0). Goal: (0, 0, 0, 1).
-- Generated by make-cp3.py.  Feed through nd-to-2d.py → hs2maze.py.

-- Outer  (pc=4): x=0 → halt, else y := 2, goto middle.
-- Middle (pc=7): y=0 → DEC x, goto outer, else z := 2, goto inner.
-- Inner  (pc=10): z=0 → DEC y, goto middle, else DEC z self-loop.

cp3 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)

-- Phase 0: y := 0
cp3 (x, y, z,    0) = cp3 (  x, y-1,   z,    2)

-- Phase 1: x := 2
cp3 (x, y, z,    2) = cp3 (x+1,   y,   z,    3)
cp3 (x, y, z,    3) = cp3 (x+1,   y,   z,    4)

-- Outer entry (pc=4)
cp3 (0, y, z,    4) = cp3 (  0,   y,   z,   11)
cp3 (x, y, z,    4) = cp3 (  x,   y,   z,    5)

-- Outer INC y chain (y := 2)
cp3 (x, y, z,    5) = cp3 (  x, y+1,   z,    6)
cp3 (x, y, z,    6) = cp3 (  x, y+1,   z,    7)

-- Middle entry (pc=7)
cp3 (x, 0, z,    7) = cp3 (x-1,   0,   z,    4)
cp3 (x, y, z,    7) = cp3 (  x,   y,   z,    8)

-- Middle INC z chain (z := 2)
cp3 (x, y, z,    8) = cp3 (  x,   y, z+1,    9)
cp3 (x, y, z,    9) = cp3 (  x,   y, z+1,   10)

-- Inner (pc=10)
cp3 (x, y, 0,   10) = cp3 (  x, y-1,   0,    7)
cp3 (x, y, z,   10) = cp3 (  x,   y, z-1,   10)

-- HALT (pc=11): bare-tuple base case for pc=1, no recursive call
cp3 (x, y, z,   11) = (  x,   y,   z,    1)
