-- cp3-4-3d.hs: O(n^3) counter-pump (3-register Minsky). n=4
-- Start: (0, 1, 0, 0). Goal: (0, 0, 0, 1).
-- Generated by make-cp3.py.  Feed through nd-to-2d.py → hs2maze.py.

-- Outer  (pc=6): x=0 → halt, else y := 4, goto middle.
-- Middle (pc=11): y=0 → DEC x, goto outer, else z := 4, goto inner.
-- Inner  (pc=16): z=0 → DEC y, goto middle, else DEC z self-loop.

cp3 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)

-- Phase 0: y := 0
cp3 (x, y, z,    0) = cp3 (  x, y-1,   z,    2)

-- Phase 1: x := 4
cp3 (x, y, z,    2) = cp3 (x+1,   y,   z,    3)
cp3 (x, y, z,    3) = cp3 (x+1,   y,   z,    4)
cp3 (x, y, z,    4) = cp3 (x+1,   y,   z,    5)
cp3 (x, y, z,    5) = cp3 (x+1,   y,   z,    6)

-- Outer entry (pc=6)
cp3 (0, y, z,    6) = cp3 (  0,   y,   z,   17)
cp3 (x, y, z,    6) = cp3 (  x,   y,   z,    7)

-- Outer INC y chain (y := 4)
cp3 (x, y, z,    7) = cp3 (  x, y+1,   z,    8)
cp3 (x, y, z,    8) = cp3 (  x, y+1,   z,    9)
cp3 (x, y, z,    9) = cp3 (  x, y+1,   z,   10)
cp3 (x, y, z,   10) = cp3 (  x, y+1,   z,   11)

-- Middle entry (pc=11)
cp3 (x, 0, z,   11) = cp3 (x-1,   0,   z,    6)
cp3 (x, y, z,   11) = cp3 (  x,   y,   z,   12)

-- Middle INC z chain (z := 4)
cp3 (x, y, z,   12) = cp3 (  x,   y, z+1,   13)
cp3 (x, y, z,   13) = cp3 (  x,   y, z+1,   14)
cp3 (x, y, z,   14) = cp3 (  x,   y, z+1,   15)
cp3 (x, y, z,   15) = cp3 (  x,   y, z+1,   16)

-- Inner (pc=16)
cp3 (x, y, 0,   16) = cp3 (  x, y-1,   0,   11)
cp3 (x, y, z,   16) = cp3 (  x,   y, z-1,   16)

-- HALT (pc=17): bare-tuple base case for pc=1, no recursive call
cp3 (x, y, z,   17) = (  x,   y,   z,    1)
