#!/usr/bin/env python3
"""make_cp3.py — Generate cp3-N-3d.hs, a 3-register O(n^3) counter-pump.

Registers: x (outer), y (middle), z (inner).  PC is the 4th slot.

Starts at (0, 1, 0, 0) and halts at (0, 1, 0, 1).  Structure:
  Phase 0: y := 0.
  Phase 1: x := n.
  Outer  (pc=p_outer):  if x=0 → halt, else y := n and goto middle.
  Middle (pc=p_middle): if y=0 → DEC x and goto outer, else z := n and goto inner.
  Inner  (pc=p_inner):  if z=0 → DEC y and goto middle, else DEC z self-loop.

Total DEC z count ≈ n^3 (n outer × n middle × n inner).

Usage: python3 make_cp3.py N [--test] > cp3-N-3d.hs

With --test, an extra output register `o` is appended (4 registers + pc = 5 slots).
`o` is incremented once per inner DEC z step, so HALT state has o = n^3.
"""
import sys

VERSION = "1.0"

VERSION_TAG = "v1.0"

USAGE = """\
Usage: make_cp3.py N [--test]
       make_cp3.py --help | -h
       make_cp3.py --version | -V

Generate cp3-N-3d.hs, a 3-register Minsky-style O(n^3) counter-pump
Haskell source.  The output is a tail-recursive
`cp3 :: (Int, Int, Int, Int) -> ...` definition with state slots
(x, y, z, pc), starting at (0, 1, 0, 0) and halting at (0, 1, 0, 1).
Pipe stdout into a file and feed it to nd-to-2d.py followed by
hs2maze.py to turn it into a repeated-maze string.

Internally the machine runs three nested loops: outer iterates DEC x
from N to 0, middle iterates DEC y from N to 0 per outer step, and
inner iterates DEC z from N to 0 per middle step.  Total inner DEC z
count is N^3, which is what gives the maze its O(n^3) length.

Positional argument:
  N             counter-pump size (N >= 1).  The walker fires inner
                DEC z exactly N^3 times before HALT.

Options:
  --test        emit a self-contained Haskell program with an extra
                output register o (= N^3 at HALT), a non-recursive
                cp3step mirror of every rule, and a `main :: IO ()`
                driver that traces every step.  Run the file directly
                via `runghc FILE.hs`; the final HALT line confirms
                o = N^3.
  -h, --help    show this message and exit.
  -V, --version show the script version (currently {tag}) and exit.
""".format(tag=VERSION_TAG)


def make(n, test=False):
    pc = 2
    p1 = list(range(pc, pc + n)); pc += n
    p_outer = pc; pc += 1
    p_oincy = list(range(pc, pc + n)); pc += n
    p_middle = pc; pc += 1
    p_mincz = list(range(pc, pc + n)); pc += n
    p_inner = pc; pc += 1
    halt_pc = pc; pc += 1

    if test:
        # 5-slot form: (x, y, z, o, pc).  `o` is the counting witness register.
        sig = "cp3 :: (Int, Int, Int, Int, Int) -> (Int, Int, Int, Int, Int)"
        step_sig = "cp3step :: (Int, Int, Int, Int, Int) -> (Int, Int, Int, Int, Int)"
        start = "(0, 1, 0, 0, 0)"
        goal = f"(0, 1, 0, {n**3}, 1)"
    else:
        sig = "cp3 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)"
        step_sig = None
        start = "(0, 1, 0, 0)"
        goal = "(0, 1, 0, 1)"

    step_rules = []  # one-step (non-recursive) mirror of cp3, only used in test mode.

    def rule(lhs_slots, rhs_slots, pc_lhs, pc_rhs):
        """Format one cp3 rule; pads `o` slot with `o` (unchanged) when test=True."""
        if test:
            lhs = ", ".join(lhs_slots + ["o"])
            rhs = ", ".join(rhs_slots + ["  o"])
            step_rules.append(f"cp3step ({lhs}, {pc_lhs:4d}) = ({rhs}, {pc_rhs:4d})")
        else:
            lhs = ", ".join(lhs_slots)
            rhs = ", ".join(rhs_slots)
        return f"cp3 ({lhs}, {pc_lhs:4d}) = cp3 ({rhs}, {pc_rhs:4d})"

    out = []
    out += [
        f"-- cp3-{n}-3d.hs: O(n^3) counter-pump (3-register Minsky). n={n}",
        f"-- Start: {start}. Goal: {goal}.",
        f"-- Generated by make_cp3.py" + (" --test" if test else "") + ".  Feed through nd-to-2d.py → hs2maze.py.",
    ]
    if test:
        out.append(f"-- Test mode: register o counts inner DEC z firings; expect o = n^3 = {n**3}.")
    out += [
        "",
        f"-- Outer  (pc={p_outer}): x=0 → halt, else y := {n}, goto middle.",
        f"-- Middle (pc={p_middle}): y=0 → DEC x, goto outer, else z := {n}, goto inner.",
        f"-- Inner  (pc={p_inner}): z=0 → DEC y, goto middle, else DEC z self-loop.",
        "",
    ]
    if test:
        out.append("import qualified System.IO")
        out.append("")
    out += [
        sig,
        "",
        f"-- Phase 0: y := 0",
        rule(["x", "y", "z"], ["  x", "y-1", "  z"], 0, p1[0]),
        "",
        f"-- Phase 1: x := {n}",
    ]
    for i, pc_i in enumerate(p1):
        nxt = p1[i + 1] if i + 1 < n else p_outer
        out.append(rule(["x", "y", "z"], ["x+1", "  y", "  z"], pc_i, nxt))
    out += [
        "",
        f"-- Outer entry (pc={p_outer})",
        rule(["0", "y", "z"], ["  0", "  y", "  z"], p_outer, halt_pc),
        rule(["x", "y", "z"], ["  x", "  y", "  z"], p_outer, p_oincy[0]),
        "",
        f"-- Outer INC y chain (y := {n})",
    ]
    for i, pc_i in enumerate(p_oincy):
        nxt = p_oincy[i + 1] if i + 1 < n else p_middle
        out.append(rule(["x", "y", "z"], ["  x", "y+1", "  z"], pc_i, nxt))
    out += [
        "",
        f"-- Middle entry (pc={p_middle})",
        rule(["x", "0", "z"], ["x-1", "  0", "  z"], p_middle, p_outer),
        rule(["x", "y", "z"], ["  x", "  y", "  z"], p_middle, p_mincz[0]),
        "",
        f"-- Middle INC z chain (z := {n})",
    ]
    for i, pc_i in enumerate(p_mincz):
        nxt = p_mincz[i + 1] if i + 1 < n else p_inner
        out.append(rule(["x", "y", "z"], ["  x", "  y", "z+1"], pc_i, nxt))
    out += [
        "",
        f"-- Inner (pc={p_inner})",
        rule(["x", "y", "0"], ["  x", "y-1", "  0"], p_inner, p_middle),
    ]
    if test:
        # Inner DEC z self-loop: also INC o.
        out.append(f"cp3 (x, y, z, o, {p_inner:4d}) = cp3 (  x,   y, z-1, o+1, {p_inner:4d})")
        step_rules.append(f"cp3step (x, y, z, o, {p_inner:4d}) = (  x,   y, z-1, o+1, {p_inner:4d})")
    else:
        out.append(rule(["x", "y", "z"], ["  x", "  y", "z-1"], p_inner, p_inner))
    out += [
        "",
        f"-- HALT (pc={halt_pc}): noop to pc=1",
        rule(["x", "y", "z"], ["  x", "  y", "  z"], halt_pc, 1),
    ]
    if test:
        # Self-contained `runghc`-friendly driver: trace every step until pc=1.
        # cp3step mirrors cp3 but without the recursive call, so the driver can
        # iterate one step at a time and check pc==1 between calls.
        out += [
            "",
            "-- cp3step: same rules as cp3, but each RHS is the bare tuple",
            "-- (no recursive call) so `main` below can drive one step at a time.",
            step_sig,
        ]
        out += step_rules
        out += [
            "",
            "-- main: print every (x, y, z, o, pc) state until pc reaches 1.",
            "main :: IO ()",
            "main = do",
            "  System.IO.hSetBuffering System.IO.stdout System.IO.LineBuffering",
            f"  loop 0 {start}",
            "  where",
            "    loop :: Int -> (Int, Int, Int, Int, Int) -> IO ()",
            "    loop k s@(_, _, _, _, pc) = do",
            "      putStrLn (show k ++ \" \" ++ show s)",
            "      if pc == 1",
            "        then putStrLn (\"HALT \" ++ show k ++ \" \" ++ show s)",
            "        else loop (k + 1) (cp3step s)",
        ]
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    if any(a in ("-h", "--help") for a in args):
        print(USAGE, end="")
        return
    if any(a in ("-V", "--version") for a in args):
        print(f"make_cp3.py v{VERSION}")
        return
    test = False
    if "--test" in args:
        test = True
        args.remove("--test")
    if len(args) != 1:
        print(USAGE, end="", file=sys.stderr)
        sys.exit(1)
    try:
        n = int(args[0])
    except ValueError:
        print(f"N must be an integer (got {args[0]!r})", file=sys.stderr)
        sys.exit(1)
    if n < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(n, test=test), end='')


if __name__ == '__main__':
    main()
