#!/usr/bin/env python3
"""make-cp3.py — Generate cp3-N-3d.hs, a 3-register O(n^3) counter-pump.

Registers: x (outer), y (middle), z (inner).  PC is the 4th slot.

Starts at (0, 1, 0, 0) and halts at (0, 1, 0, 1).  Structure:
  Phase 0: y := 0.
  Phase 1: x := n.
  Outer  (pc=p_outer):  if x=0 → halt, else y := n and goto middle.
  Middle (pc=p_middle): if y=0 → DEC x and goto outer, else z := n and goto inner.
  Inner  (pc=p_inner):  if z=0 → DEC y and goto middle, else DEC z self-loop.

Total DEC z count ≈ n^3 (n outer × n middle × n inner).

Usage: python3 make-cp3.py N [--test] > cp3-N-3d.hs

With --test, an extra output register `o` is appended (4 registers + pc = 5 slots).
`o` is incremented once per inner DEC z step, so HALT state has o = n^3.
"""
import sys

VERSION = "1.2"

VERSION_TAG = "v1.2"

USAGE = """\
Usage: make-cp3.py N [--test]
       make-cp3.py --help | -h
       make-cp3.py --version | -V

Generate cp3-N-3d.hs, a 3-register Minsky-style O(n^3) counter-pump
Haskell source.  The output is a tail-recursive
`cp3 :: (Int, Int, Int, Int) -> ...` definition with state slots
(x, y, z, pc), starting at (0, 1, 0, 0) and halting at (0, 1, 0, 1).
Pipe stdout into a file and feed it to nd-to-2d.py followed by
hs2maze.py to turn it into a repeated-maze string.

Internally the machine runs three nested loops: outer iterates DEC x
from N to 0, middle iterates DEC y from N to 0 per outer step, and
inner iterates DEC z from N to 0 per middle step.  Total inner DEC z
count is N^3, which is what gives the maze its O(n^3) length.

Positional argument:
  N             counter-pump size (N >= 1).  The walker fires inner
                DEC z exactly N^3 times before HALT.

Options:
  --test        emit a self-contained runnable Haskell with an extra
                output register o.  The HALT rule returns a bare
                tuple, and a `main :: IO ()` prints the final state.
                Run via `runghc FILE.hs`; output is `(0,0,0,N^3,1)`
                on a single line, confirming o = N^3.
  -h, --help    show this message and exit.
  -V, --version show the script version (currently {tag}) and exit.
""".format(tag=VERSION_TAG)


def make(n, test=False):
    pc = 2
    p1 = list(range(pc, pc + n)); pc += n
    p_outer = pc; pc += 1
    p_oincy = list(range(pc, pc + n)); pc += n
    p_middle = pc; pc += 1
    p_mincz = list(range(pc, pc + n)); pc += n
    p_inner = pc; pc += 1
    halt_pc = pc; pc += 1

    if test:
        # 5-slot form: (x, y, z, o, pc).  `o` is the counting witness register.
        sig = "cp3 :: (Int, Int, Int, Int, Int) -> (Int, Int, Int, Int, Int)"
        start = "(0, 1, 0, 0, 0)"
        goal = f"(0, 0, 0, {n**3}, 1)"
    else:
        sig = "cp3 :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)"
        start = "(0, 1, 0, 0)"
        goal = "(0, 0, 0, 1)"

    def rule(lhs_slots, rhs_slots, pc_lhs, pc_rhs, halt=False):
        """Format one cp3 rule; pads `o` slot with `o` (unchanged) when test=True.
        If halt=True, emit RHS as a bare tuple (no `cp3` prefix) — true Haskell
        base case usable directly under runghc.  In test mode the recursive
        RHS goes through `cp3_` so Debug.Trace prints every step."""
        if test:
            lhs = ", ".join(lhs_slots + ["o"])
            rhs = ", ".join(rhs_slots + ["  o"])
        else:
            lhs = ", ".join(lhs_slots)
            rhs = ", ".join(rhs_slots)
        if halt:
            rhs_prefix = ""
        elif test:
            rhs_prefix = "cp3_ "
        else:
            rhs_prefix = "cp3 "
        return f"cp3 ({lhs}, {pc_lhs:4d}) = {rhs_prefix}({rhs}, {pc_rhs:4d})"

    out = []
    out += [
        f"-- cp3-{n}-3d.hs: O(n^3) counter-pump (3-register Minsky). n={n}",
        f"-- Start: {start}. Goal: {goal}.",
        f"-- Generated by make-cp3.py" + (" --test" if test else "") + ".  Feed through nd-to-2d.py → hs2maze.py.",
    ]
    if test:
        out.append(f"-- Test mode: register o counts inner DEC z firings; expect o = n^3 = {n**3}.")
    out += [
        "",
        f"-- Outer  (pc={p_outer}): x=0 → halt, else y := {n}, goto middle.",
        f"-- Middle (pc={p_middle}): y=0 → DEC x, goto outer, else z := {n}, goto inner.",
        f"-- Inner  (pc={p_inner}): z=0 → DEC y, goto middle, else DEC z self-loop.",
        "",
    ]
    if test:
        out += ["import Debug.Trace (trace)", ""]
    out += [
        sig,
        "",
        f"-- Phase 0: y := 0",
        rule(["x", "y", "z"], ["  x", "y-1", "  z"], 0, p1[0]),
        "",
        f"-- Phase 1: x := {n}",
    ]
    for i, pc_i in enumerate(p1):
        nxt = p1[i + 1] if i + 1 < n else p_outer
        out.append(rule(["x", "y", "z"], ["x+1", "  y", "  z"], pc_i, nxt))
    out += [
        "",
        f"-- Outer entry (pc={p_outer})",
        rule(["0", "y", "z"], ["  0", "  y", "  z"], p_outer, halt_pc),
        rule(["x", "y", "z"], ["  x", "  y", "  z"], p_outer, p_oincy[0]),
        "",
        f"-- Outer INC y chain (y := {n})",
    ]
    for i, pc_i in enumerate(p_oincy):
        nxt = p_oincy[i + 1] if i + 1 < n else p_middle
        out.append(rule(["x", "y", "z"], ["  x", "y+1", "  z"], pc_i, nxt))
    out += [
        "",
        f"-- Middle entry (pc={p_middle})",
        rule(["x", "0", "z"], ["x-1", "  0", "  z"], p_middle, p_outer),
        rule(["x", "y", "z"], ["  x", "  y", "  z"], p_middle, p_mincz[0]),
        "",
        f"-- Middle INC z chain (z := {n})",
    ]
    for i, pc_i in enumerate(p_mincz):
        nxt = p_mincz[i + 1] if i + 1 < n else p_inner
        out.append(rule(["x", "y", "z"], ["  x", "  y", "z+1"], pc_i, nxt))
    out += [
        "",
        f"-- Inner (pc={p_inner})",
        rule(["x", "y", "0"], ["  x", "y-1", "  0"], p_inner, p_middle),
    ]
    if test:
        # Inner DEC z self-loop: also INC o.  RHS goes through cp3_ trace wrapper.
        out.append(f"cp3 (x, y, z, o, {p_inner:4d}) = cp3_ (  x,   y, z-1, o+1, {p_inner:4d})")
    else:
        out.append(rule(["x", "y", "z"], ["  x", "  y", "z-1"], p_inner, p_inner))
    out += [
        "",
        f"-- HALT (pc={halt_pc}): bare-tuple base case for pc=1, no recursive call",
        rule(["x", "y", "z"], ["  x", "  y", "  z"], halt_pc, 1, halt=True),
    ]
    if test:
        out += [
            "",
            "-- cp3_ : trace wrapper.  Every recursive RHS goes through cp3_ so",
            "-- Debug.Trace.trace prints each intermediate state to stderr.",
            "cp3_ :: (Int, Int, Int, Int, Int) -> (Int, Int, Int, Int, Int)",
            "cp3_ args = trace (show args) (cp3 args)",
            "",
            f"-- main: trace every step from {start}, then print the final state.",
            f"-- Expected final state: {goal}.",
            "main :: IO ()",
            f"main = print (cp3_ {start})",
        ]
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    if any(a in ("-h", "--help") for a in args):
        print(USAGE, end="")
        return
    if any(a in ("-V", "--version") for a in args):
        print(f"make-cp3.py v{VERSION}")
        return
    test = False
    if "--test" in args:
        test = True
        args.remove("--test")
    if len(args) != 1:
        print(USAGE, end="", file=sys.stderr)
        sys.exit(1)
    try:
        n = int(args[0])
    except ValueError:
        print(f"N must be an integer (got {args[0]!r})", file=sys.stderr)
        sys.exit(1)
    if n < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(n, test=test), end='')


if __name__ == '__main__':
    main()
