#!/usr/bin/env python3
"""runhs.py — Run a Minsky-style Haskell state machine and report the
trace length / final state.

Accepts Haskell files in the `hs2maze.py` / `nd-to-2d.py` input format:
    fn :: (Int, Int, ..., Int) -> (Int, Int, ..., Int)
    fn (pat_0, ..., pat_{n-1}, pat_pc) = fn (rhs_0, ..., rhs_{n-1}, rhs_pc)

These files define a single step-function rather than a `main`.  runhs.py
rewrites each equation `fn (LHS) = fn (RHS)` into a one-step form
`fnStep (LHS) = (RHS)`, adds a terminator equation at pc=1, wraps with a
main loop that iterates fnStep from the conventional initial state
`(0, 1, 0, ..., 0, 0)`, and hands the result to `runghc`.

Usage:
    python3 runhs.py FILE.hs             run, print HALT step count and state
    python3 runhs.py FILE.hs --trace     also print every intermediate state
    python3 runhs.py FILE.hs --limit N   halt if step count exceeds N
                                         (default: 5_000_000)

The wrapped Haskell is written to a temp file and executed via `runghc`;
use `--save` to additionally copy it next to the input as
`<stem>_runable.hs` for inspection.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile


SIG_RE = re.compile(
    r"^(?P<name>[a-zA-Z_][a-zA-Z0-9_']*)\s*::\s*"
    r"\((?P<tup>[^)]*)\)\s*->\s*\([^)]*\)\s*$"
)
EQ_RE = re.compile(
    r"^(?P<name>[a-zA-Z_][a-zA-Z0-9_']*)\s*"
    r"(?P<lhs>\([^)]*\))\s*=\s*"
    r"(?:[a-zA-Z_][a-zA-Z0-9_']*\s*)?"
    r"(?P<rhs>\([^)]*\))\s*$"
)


def strip_comment(line: str) -> str:
    i = line.find("--")
    return line[:i] if i >= 0 else line


def parse_arity(text: str) -> int | None:
    """Return n (number of register slots + 1 for pc) inferred from the
    type signature, or from the first equation if the signature is
    missing."""
    for raw in text.splitlines():
        line = strip_comment(raw).strip()
        if not line:
            continue
        m = SIG_RE.match(line)
        if m:
            return len([t for t in m.group("tup").split(",") if t.strip()])
        m = EQ_RE.match(line)
        if m:
            # Count commas + 1 in the LHS tuple.
            lhs = m.group("lhs")[1:-1]  # strip parens
            return len([t for t in lhs.split(",") if t.strip()])
    return None


def rewrite(text: str, arity: int, trace: bool, start_override: str | None = None) -> str:
    """Rewrite the Haskell into a step-function form + driver.

    trace=True -> print every intermediate state.
    start_override = explicit "(..., ..., ...)" tuple (or None for default).
    """
    lines_out: list[str] = []
    step_name = "fnStep"
    fn_name: str | None = None
    halt_added = False

    lines_out.append(f"-- Generated by runhs.py from a Minsky-style Haskell source.")
    lines_out.append("import System.IO (hSetBuffering, stdout, BufferMode(LineBuffering))")
    lines_out.append(f"{step_name} :: {'(' + ', '.join(['Int'] * arity) + ')'} -> {'(' + ', '.join(['Int'] * arity) + ')'}")

    for raw in text.splitlines():
        line = strip_comment(raw).strip()
        if not line or "::" in line:
            continue
        m = EQ_RE.match(line)
        if not m:
            continue
        if fn_name is None:
            fn_name = m.group("name")
        if m.group("name") != fn_name:
            continue  # ignore unrelated function
        lines_out.append(f"{step_name} {m.group('lhs')} = {m.group('rhs')}")

    # Terminator so that pc=1 always matches and returns the state as-is.
    halt_pat = "(" + ", ".join(
        [f"x{i}" for i in range(arity - 1)] + ["1"]
    ) + ")"
    halt_rhs = "(" + ", ".join(
        [f"x{i}" for i in range(arity - 1)] + ["1"]
    ) + ")"
    lines_out.append(f"{step_name} {halt_pat} = {halt_rhs}")

    # Driver.  Default initial state = (0, 0, 0, ..., 0) matching the
    # new (0,0,W0) maze start convention.  Override with --start "(...)"
    # for legacy programs that expect e.g. (0, 1, 0, ..., 0).
    if start_override is not None:
        init_tuple = start_override
    else:
        init_tuple = "(" + ", ".join(["0"] * arity) + ")"

    lines_out.append("")
    lines_out.append("main :: IO ()")
    lines_out.append(f"main = do")
    lines_out.append(f"  hSetBuffering stdout LineBuffering")
    lines_out.append(f"  driver 0 {init_tuple}")
    lines_out.append("  where")
    # HALT pattern: last element = 1.
    pc_guard = ", ".join(["_"] * (arity - 1)) + ", 1"
    lines_out.append(f"    driver :: Int -> {'(' + ', '.join(['Int'] * arity) + ')'} -> IO ()")
    lines_out.append(f"    driver n s@({pc_guard}) = putStrLn (\"HALT \" ++ show n ++ \" \" ++ show s)")
    lines_out.append(f"    driver n s | n > LIMIT_SENTINEL = putStrLn (\"TIMEOUT \" ++ show n ++ \" \" ++ show s)")
    if trace:
        lines_out.append(f"    driver n s = do putStrLn (show n ++ \" \" ++ show s); driver (n+1) ({step_name} s)")
    else:
        lines_out.append(f"    driver n s = driver (n+1) ({step_name} s)")

    return "\n".join(lines_out) + "\n"


VERSION = "1.0"


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)
    if sys.argv[1] in ("-V", "--version"):
        print(f"runhs.py v{VERSION}")
        sys.exit(0)

    path = sys.argv[1]
    trace = "--trace" in sys.argv
    save = "--save" in sys.argv
    limit = 5_000_000
    start_override: str | None = None
    for i, a in enumerate(sys.argv):
        if a == "--limit" and i + 1 < len(sys.argv):
            limit = int(sys.argv[i + 1])
        elif a == "--start" and i + 1 < len(sys.argv):
            start_override = sys.argv[i + 1]

    with open(path) as f:
        text = f.read()

    arity = parse_arity(text)
    if arity is None or arity < 2:
        print(f"runhs.py: could not detect tuple arity in {path}", file=sys.stderr)
        sys.exit(2)

    wrapped = rewrite(text, arity, trace, start_override).replace("LIMIT_SENTINEL", str(limit))

    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".hs", delete=False, prefix="runhs_"
    )
    tmp.write(wrapped)
    tmp.close()

    saved_path: str | None = None
    if save:
        stem, _ = os.path.splitext(path)
        saved_path = f"{stem}_runable.hs"
        with open(saved_path, "w") as f:
            f.write(wrapped)
        print(f"runhs.py: wrapped Haskell saved to {saved_path}", file=sys.stderr)

    try:
        result = subprocess.run(
            ["runghc", tmp.name],
            stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr,
        )
        sys.exit(result.returncode)
    finally:
        os.unlink(tmp.name)


if __name__ == "__main__":
    main()
