#!/usr/bin/env python3
"""Generate md[N].hs for hs2maze: Minsky Doubling Machine with N cycles of y ↦ 2y+1.

Usage: python3 make-minsky-doubling.py N
  Writes maze/minsky-doubling/mdN.hs to stdout.
"""
import sys


def make(k):
    y_seq = [1]
    for i in range(k):
        y_seq.append(2 * y_seq[-1] + 1)

    # Compute nx/ny/bridge ports
    ns = 0
    ns_ym = []  # N/S index for each cycle's y-1
    ns_yp = []  # N/S index for each cycle's y+1
    for ci in range(k):
        ns_ym.append(ns); ns += 1
        ns_yp.append(ns); ns += 1
    ns_drain = ns; ns += 1
    ns_exits = []
    for ci in range(k):
        ns_exits.append(ns); ns += 1
    ns_drain_exit = ns; ns += 1

    ny_ports = []
    nx_ports = []
    bridge_ports = []
    for ci in range(k):
        xfer_pc = 4 if ci == 0 else 5 * ci + 4
        ny_ports.append(f"N{ns_ym[ci]}-N{ns_exits[ci]}")
        bridge_ports.append(f"S{ns_exits[ci]}-W{xfer_pc}")
        next_start = 5 * (ci + 1) + 1 if ci < k - 1 else 5 * k + 1
        nx_ports.append(f"E{xfer_pc}-E{next_start}")
    ny_ports.append(f"N{ns_drain}-N{ns_drain_exit}")
    bridge_ports.append(f"S{ns_drain_exit}-W1")

    # Header
    y_chain = ' → '.join(str(v) for v in y_seq)
    lines = []
    lines.append(f"-- md{k}.hs: Minsky Doubling Machine (k={k} cycles of y ↦ 2y+1)")
    lines.append(f"-- Input for hs2maze.py (generates normal block ports only)")
    lines.append(f"--")
    lines.append(f"-- Computation: y = {y_chain}, then drain y to 0.")
    lines.append(f"-- Result: 2^({k}+1) - 1 = {y_seq[-1]}")
    lines.append(f"--")
    lines.append(f"-- Structure per cycle (start at pc=S):")
    lines.append(f"--   S:   x+1       (inc x, part 1 of doubling)")
    lines.append(f"--   S+1: x+1       (inc x, part 2 of doubling)")
    lines.append(f"--   S+2: y-1 → S   (dec y, loop back; ny fires at y=0)")
    lines.append(f"--   S+3: x-1       (dec x, transfer x→y)")
    lines.append(f"--   S+4: y+1 → S+3 (inc y, transfer loop; nx fires at x=0)")
    lines.append(f"--")
    lines.append(f"-- Additional ports needed (not generated by hs2maze):")
    lines.append(f"--   ny: {', '.join(ny_ports)}")
    lines.append(f"--   nx: {', '.join(nx_ports)}")
    lines.append(f"--   normal (bridge): {', '.join(bridge_ports)}")
    lines.append(f"--")
    lines.append(f"-- Usage: python3 hs2maze.py md{k}.hs")
    lines.append(f"")
    lines.append(f"md :: (Int, Int, Int) -> (Int, Int, Int)")

    # Cycles
    for ci in range(k):
        if ci == 0:
            S = 0
            pcs = [0, 2, 3, 4, 5]
        else:
            S = 5 * ci + 1
            pcs = [S, S+1, S+2, S+3, S+4]
        lines.append(f"")
        lines.append(f"-- Cycle {ci} (y ↦ 2y+1)")
        lines.append(f"md (x, y, {pcs[0]}) = md (x+1, y,   {pcs[1]})")
        lines.append(f"md (x, y, {pcs[1]}) = md (x+1, y,   {pcs[2]})")
        lines.append(f"md (x, y, {pcs[2]}) = md (x,   y-1, {pcs[0]})")
        lines.append(f"md (x, y, {pcs[3]}) = md (x-1, y,   {pcs[4]})")
        lines.append(f"md (x, y, {pcs[4]}) = md (x,   y+1, {pcs[3]})")

    # Drain
    D = 5 * k + 1
    lines.append(f"")
    lines.append(f"-- Drain (y → 0)")
    lines.append(f"md (x, y, {D}) = md (x,   y-1, {D})")

    return '\n'.join(lines) + '\n'


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} N", file=sys.stderr)
        sys.exit(1)
    k = int(sys.argv[1])
    if k < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(k), end='')


if __name__ == '__main__':
    main()
