#!/usr/bin/env python3
"""make-minsky-doubling.py — Generate mdN.hs, a Minsky 2-counter doubling machine.

Each cycle's doubling subroutine takes (x, y) = (0, Y) at pc=S, runs:
    repeat: y:=y-1; x:=x+2            until y=0     (doubling phase)
    repeat: x:=x-1; y:=y+1            until x=0     (transfer phase)
so y at end of cycle = 2*Y exactly.  The y-DEC zero-test fires before
the INC-x pair, so the "extra iteration" overshoot is avoided.  After
K cycles the y register goes
    1 → 2 → 4 → 8 → 16 → ... = 2^i.

Usage: python3 make-minsky-doubling.py N [--test] > mdN.hs
"""
import sys

VERSION = "1.3"

USAGE = """\
Usage: make-minsky-doubling.py N [--test]
       make-minsky-doubling.py --help | -h
       make-minsky-doubling.py --version | -V

Generate mdN.hs, a 2-register Minsky-style doubling machine that runs
N cycles of a "INC-x-twice-while-DEC-y, then transfer x→y" subroutine.
The output is a tail-recursive `md :: (Int, Int, Int) -> ...` definition
with state slots (x, y, pc), starting at (0, 1, 0) and halting at
(0, 0, 1).  Zero-branch rules (`(x, 0, ...)` and `(0, y, ...)`) are
emitted, so feeding the file directly to hs2maze.py auto-generates the
required nx / ny / bridge ports.

Internally each cycle does:
  S:   y-1 → S+1           -- dec y, then to INC-x pair; ny: y=0 → S+3
  S+1: x+1 → S+2           -- inc x, part 1 of doubling
  S+2: x+1 → S             -- inc x, part 2 of doubling, loop back
  S+3: x-1 → S+4           -- dec x, transfer x→y; nx: x=0 → next cycle
  S+4: y+1 → S+3           -- inc y, transfer loop
plus a final pc=D drain that DECs y until y=0, then ny → pc=1 (HALT).

At the Haskell-register level, each cycle maps Y ↦ 2Y exactly, so the
y-register sequence is 1 → 2 → 4 → 8 → ... = 2^i.

Positional argument:
  N             number of doubling cycles (N >= 1).  Path length
                grows as O(2^N).

Options:
  --test        emit a self-contained runnable Haskell with an extra
                witness register o counting productive doubling-phase
                DEC y operations (= 2^N − 1).  The HALT rule returns
                a bare tuple, and a `main :: IO ()` prints the final
                state.  Run via `runghc FILE.hs`; output is
                `(0,0,2^N − 1,1)` on a single line.
  -h, --help    show this message and exit.
  -V, --version show the script version (currently v{version}) and
                exit.
""".format(version=VERSION)


def make(k, test=False):
    # Haskell-register-level y sequence: y_0 = 1, y_{i+1} = 2*y_i.
    y_seq = [1]
    for _ in range(k):
        y_seq.append(2 * y_seq[-1])
    expected_o = sum(y_seq[:-1])  # productive DEC y in doubling phases = 2^k - 1

    if test:
        sig = "md :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)"
        start = "(0, 1, 0, 0)"
        goal = f"(0, 0, {expected_o}, 1)"
    else:
        sig = "md :: (Int, Int, Int) -> (Int, Int, Int)"
        start = "(0, 1, 0)"
        goal = "(0, 0, 1)"

    def rule(lhs_x, lhs_y, rhs_x, rhs_y, pc_lhs, pc_rhs, inc_o=False, halt=False):
        """If halt=True, RHS is emitted as a bare tuple (true Haskell base case).
        In test mode, the recursive RHS goes through `md_` so Debug.Trace prints
        every step."""
        if test:
            o_rhs = "o+1" if inc_o else "  o"
            lhs = f"{lhs_x}, {lhs_y}, o"
            rhs = f"{rhs_x}, {rhs_y}, {o_rhs}"
        else:
            lhs = f"{lhs_x}, {lhs_y}"
            rhs = f"{rhs_x}, {rhs_y}"
        if halt:
            rhs_prefix = ""
        elif test:
            rhs_prefix = "md_ "
        else:
            rhs_prefix = "md "
        return f"md ({lhs}, {pc_lhs:4d}) = {rhs_prefix}({rhs}, {pc_rhs:4d})"

    y_chain = ' → '.join(str(v) for v in y_seq)
    lines = []
    lines.append(f"-- md{k}.hs: Minsky Doubling Machine (k={k} cycles, Y ↦ 2Y exactly)")
    lines.append(f"-- Start: {start}. Goal: {goal}.")
    lines.append(
        "-- Generated by make-minsky-doubling.py"
        + (" --test" if test else "")
        + ".  Feed through hs2maze.py to obtain the maze."
    )
    if test:
        lines.append(
            f"-- Test mode: register o counts productive DEC y in doubling phases; "
            f"expect o = 2^{k} − 1 = {expected_o}."
        )
    lines.append(f"--")
    lines.append(f"-- y-register sequence: {y_chain}, then drain y to 0.")
    lines.append(f"-- Final pre-drain y = 2^{k} = {y_seq[-1]}")
    lines.append(f"--")
    lines.append(f"-- Structure per cycle (start at pc=S):")
    lines.append(f"--   S:   y-1 → S+1; ny: y=0 → S+3 (zero-test BEFORE INC x pair)")
    lines.append(f"--   S+1: x+1 → S+2           (inc x, part 1 of doubling)")
    lines.append(f"--   S+2: x+1 → S             (inc x, part 2; loop back to y-DEC)")
    lines.append(f"--   S+3: x-1 → S+4; nx: x=0 → next-S (transfer x→y)")
    lines.append(f"--   S+4: y+1 → S+3           (inc y, transfer loop)")
    lines.append(f"-- Drain (pc=D): y-1 → D; ny: y=0 → 1 (HALT)")
    lines.append("")

    if test:
        lines.append("import Debug.Trace (trace)")
        lines.append("")

    lines.append(sig)

    # Cycles
    for ci in range(k):
        if ci == 0:
            S = 0
            pcs = [0, 2, 3, 4, 5]
        else:
            S = 5 * ci + 1
            pcs = [S, S+1, S+2, S+3, S+4]
        next_S = 5 * (ci + 1) + 1 if ci < k - 1 else 5 * k + 1  # next cycle or drain
        lines.append("")
        lines.append(f"-- Cycle {ci} (Y={y_seq[ci]} → {y_seq[ci+1]}); xfer at pc={pcs[3]}, exit to pc={next_S}")
        # ny zero-branch FIRST (so Haskell pattern match picks literal 0 before var).
        # Putting the y-DEC zero-test at pcs[0], BEFORE the INC-x pair, ensures
        # the loop exits the moment y=0 — no extra INC x overshoot, so y_new = 2*Y exactly.
        lines.append(rule("x", "0", "  x", "  0", pcs[0], pcs[3]))             # ny: y=0 → transfer (skip INC x)
        lines.append(rule("x", "y", "  x", "y-1", pcs[0], pcs[1], inc_o=True))  # DEC y, then INC x pair
        lines.append(rule("x", "y", "x+1", "  y", pcs[1], pcs[2]))             # INC x part 1
        lines.append(rule("x", "y", "x+1", "  y", pcs[2], pcs[0]))             # INC x part 2; loop back to y-DEC
        lines.append(rule("0", "y", "  0", "  y", pcs[3], next_S))             # nx: x=0 → next cycle / drain
        lines.append(rule("x", "y", "x-1", "  y", pcs[3], pcs[4]))             # DEC x (transfer)
        lines.append(rule("x", "y", "  x", "y+1", pcs[4], pcs[3]))             # INC y (transfer)

    # Drain
    D = 5 * k + 1
    lines.append("")
    lines.append(f"-- Drain (pc={D}): DEC y to 0, then ny → HALT (bare-tuple base case)")
    lines.append(rule("x", "0", "  x", "  0", D, 1, halt=True))                 # ny drain → HALT base case
    lines.append(rule("x", "y", "  x", "y-1", D, D))

    if test:
        lines.append("")
        lines.append("-- md_ : trace wrapper.  Every recursive RHS goes through md_ so")
        lines.append("-- Debug.Trace.trace prints each intermediate state to stderr.")
        lines.append("md_ :: (Int, Int, Int, Int) -> (Int, Int, Int, Int)")
        lines.append("md_ args = trace (show args) (md args)")
        lines.append("")
        lines.append(f"-- main: trace every step from {start}, then print the final state.")
        lines.append(f"-- Expected final state: {goal}.")
        lines.append("main :: IO ()")
        lines.append(f"main = print (md_ {start})")

    return '\n'.join(lines) + '\n'


def main():
    args = sys.argv[1:]
    if any(a in ("-h", "--help") for a in args):
        print(USAGE, end="")
        return
    if any(a in ("-V", "--version") for a in args):
        print(f"make-minsky-doubling.py v{VERSION}")
        return
    test = False
    if "--test" in args:
        test = True
        args.remove("--test")
    if len(args) != 1:
        print(USAGE, end="", file=sys.stderr)
        sys.exit(1)
    try:
        n = int(args[0])
    except ValueError:
        print(f"N must be an integer (got {args[0]!r})", file=sys.stderr)
        sys.exit(1)
    if n < 1:
        print("N must be >= 1", file=sys.stderr)
        sys.exit(1)
    print(make(n, test=test), end='')


if __name__ == '__main__':
    main()
