-- md4.hs: Minsky Doubling Machine (k=4 cycles, Y ↦ 2Y exactly)
-- Start: (0, 1, 0). Goal: (0, 0, 1).
-- Generated by make-minsky-doubling.py.  Feed through hs2maze.py to obtain the maze.
--
-- y-register sequence: 1 → 2 → 4 → 8 → 16, then drain y to 0.
-- Final pre-drain y = 2^4 = 16
--
-- Structure per cycle (start at pc=S):
--   S:   y-1 → S+1; ny: y=0 → S+3 (zero-test BEFORE INC x pair)
--   S+1: x+1 → S+2           (inc x, part 1 of doubling)
--   S+2: x+1 → S             (inc x, part 2; loop back to y-DEC)
--   S+3: x-1 → S+4; nx: x=0 → next-S (transfer x→y)
--   S+4: y+1 → S+3           (inc y, transfer loop)
-- Drain (pc=D): y-1 → D; ny: y=0 → 1 (HALT)

md :: (Int, Int, Int) -> (Int, Int, Int)

-- Cycle 0 (Y=1 → 2); xfer at pc=4, exit to pc=6
md (x, 0,    0) = md (  x,   0,    4)
md (x, y,    0) = md (  x, y-1,    2)
md (x, y,    2) = md (x+1,   y,    3)
md (x, y,    3) = md (x+1,   y,    0)
md (0, y,    4) = md (  0,   y,    6)
md (x, y,    4) = md (x-1,   y,    5)
md (x, y,    5) = md (  x, y+1,    4)

-- Cycle 1 (Y=2 → 4); xfer at pc=9, exit to pc=11
md (x, 0,    6) = md (  x,   0,    9)
md (x, y,    6) = md (  x, y-1,    7)
md (x, y,    7) = md (x+1,   y,    8)
md (x, y,    8) = md (x+1,   y,    6)
md (0, y,    9) = md (  0,   y,   11)
md (x, y,    9) = md (x-1,   y,   10)
md (x, y,   10) = md (  x, y+1,    9)

-- Cycle 2 (Y=4 → 8); xfer at pc=14, exit to pc=16
md (x, 0,   11) = md (  x,   0,   14)
md (x, y,   11) = md (  x, y-1,   12)
md (x, y,   12) = md (x+1,   y,   13)
md (x, y,   13) = md (x+1,   y,   11)
md (0, y,   14) = md (  0,   y,   16)
md (x, y,   14) = md (x-1,   y,   15)
md (x, y,   15) = md (  x, y+1,   14)

-- Cycle 3 (Y=8 → 16); xfer at pc=19, exit to pc=21
md (x, 0,   16) = md (  x,   0,   19)
md (x, y,   16) = md (  x, y-1,   17)
md (x, y,   17) = md (x+1,   y,   18)
md (x, y,   18) = md (x+1,   y,   16)
md (0, y,   19) = md (  0,   y,   21)
md (x, y,   19) = md (x-1,   y,   20)
md (x, y,   20) = md (  x, y+1,   19)

-- Drain (pc=21): DEC y to 0, then ny → HALT (bare-tuple base case)
md (x, 0,   21) = (  x,   0,    1)
md (x, y,   21) = md (  x, y-1,   21)
