-- md5.hs: Minsky Doubling Machine (k=5 cycles, Y ↦ 2Y exactly)
-- Start: (0, 0, 0). Goal: (0, 0, 1).
-- Generated by make-minsky-doubling.py.  Feed through hs2maze.py to obtain the maze.
--
-- y-register sequence: 1 → 2 → 4 → 8 → 16 → 32, then drain y to 0.
-- Final pre-drain y = 2^5 = 32
--
-- Structure per cycle (start at pc=S):
--   S:   y-1 → S+1; ny: y=0 → S+3 (zero-test BEFORE INC x pair)
--   S+1: x+1 → S+2           (inc x, part 1 of doubling)
--   S+2: x+1 → S             (inc x, part 2; loop back to y-DEC)
--   S+3: x-1 → S+4; nx: x=0 → next-S (transfer x→y)
--   S+4: y+1 → S+3           (inc y, transfer loop)
-- Drain (pc=D): y-1 → D; ny: y=0 → 1 (HALT)

md :: (Int, Int, Int) -> (Int, Int, Int)

-- Phase 0 (pc=0): INC y to seed y := 1, goto cycle 0
md (x, y,    0) = md (  x, y+1,    2)

-- Cycle 0 (Y=1 → 2); xfer at pc=5, exit to pc=7
md (x, 0,    2) = md (  x,   0,    5)
md (x, y,    2) = md (  x, y-1,    3)
md (x, y,    3) = md (x+1,   y,    4)
md (x, y,    4) = md (x+1,   y,    2)
md (0, y,    5) = md (  0,   y,    7)
md (x, y,    5) = md (x-1,   y,    6)
md (x, y,    6) = md (  x, y+1,    5)

-- Cycle 1 (Y=2 → 4); xfer at pc=10, exit to pc=12
md (x, 0,    7) = md (  x,   0,   10)
md (x, y,    7) = md (  x, y-1,    8)
md (x, y,    8) = md (x+1,   y,    9)
md (x, y,    9) = md (x+1,   y,    7)
md (0, y,   10) = md (  0,   y,   12)
md (x, y,   10) = md (x-1,   y,   11)
md (x, y,   11) = md (  x, y+1,   10)

-- Cycle 2 (Y=4 → 8); xfer at pc=15, exit to pc=17
md (x, 0,   12) = md (  x,   0,   15)
md (x, y,   12) = md (  x, y-1,   13)
md (x, y,   13) = md (x+1,   y,   14)
md (x, y,   14) = md (x+1,   y,   12)
md (0, y,   15) = md (  0,   y,   17)
md (x, y,   15) = md (x-1,   y,   16)
md (x, y,   16) = md (  x, y+1,   15)

-- Cycle 3 (Y=8 → 16); xfer at pc=20, exit to pc=22
md (x, 0,   17) = md (  x,   0,   20)
md (x, y,   17) = md (  x, y-1,   18)
md (x, y,   18) = md (x+1,   y,   19)
md (x, y,   19) = md (x+1,   y,   17)
md (0, y,   20) = md (  0,   y,   22)
md (x, y,   20) = md (x-1,   y,   21)
md (x, y,   21) = md (  x, y+1,   20)

-- Cycle 4 (Y=16 → 32); xfer at pc=25, exit to pc=27
md (x, 0,   22) = md (  x,   0,   25)
md (x, y,   22) = md (  x, y-1,   23)
md (x, y,   23) = md (x+1,   y,   24)
md (x, y,   24) = md (x+1,   y,   22)
md (0, y,   25) = md (  0,   y,   27)
md (x, y,   25) = md (x-1,   y,   26)
md (x, y,   26) = md (  x, y+1,   25)

-- Drain (pc=27): DEC y to 0, then ny → HALT (bare-tuple base case)
md (x, 0,   27) = (  x,   0,    1)
md (x, y,   27) = md (  x, y-1,   27)
