-- md5.hs: Minsky Doubling Machine (k=5 cycles of y ↦ 2y+1)
-- Input for hs2maze.py (generates normal block ports only)
--
-- Computation: y = 1 → 3 → 7 → 15 → 31 → 63, then drain y to 0.
-- Result: 2^(5+1) - 1 = 63
--
-- Structure per cycle (start at pc=S):
--   S:   x+1       (inc x, part 1 of doubling)
--   S+1: x+1       (inc x, part 2 of doubling)
--   S+2: y-1 → S   (dec y, loop back; ny fires at y=0)
--   S+3: x-1       (dec x, transfer x→y)
--   S+4: y+1 → S+3 (inc y, transfer loop; nx fires at x=0)
--
-- Additional ports needed (not generated by hs2maze):
--   ny: N0-N11, N2-N12, N4-N13, N6-N14, N8-N15, N10-N16
--   nx: E4-E6, E9-E11, E14-E16, E19-E21, E24-E26
--   normal (bridge): S11-W4, S12-W9, S13-W14, S14-W19, S15-W24, S16-W1
--
-- Usage: python3 hs2maze.py md5.hs

md :: (Int, Int, Int) -> (Int, Int, Int)

-- Cycle 0 (y ↦ 2y+1)
md (x, y, 0) = md (x+1, y,   2)
md (x, y, 2) = md (x+1, y,   3)
md (x, y, 3) = md (x,   y-1, 0)
md (x, y, 4) = md (x-1, y,   5)
md (x, y, 5) = md (x,   y+1, 4)

-- Cycle 1 (y ↦ 2y+1)
md (x, y, 6) = md (x+1, y,   7)
md (x, y, 7) = md (x+1, y,   8)
md (x, y, 8) = md (x,   y-1, 6)
md (x, y, 9) = md (x-1, y,   10)
md (x, y, 10) = md (x,   y+1, 9)

-- Cycle 2 (y ↦ 2y+1)
md (x, y, 11) = md (x+1, y,   12)
md (x, y, 12) = md (x+1, y,   13)
md (x, y, 13) = md (x,   y-1, 11)
md (x, y, 14) = md (x-1, y,   15)
md (x, y, 15) = md (x,   y+1, 14)

-- Cycle 3 (y ↦ 2y+1)
md (x, y, 16) = md (x+1, y,   17)
md (x, y, 17) = md (x+1, y,   18)
md (x, y, 18) = md (x,   y-1, 16)
md (x, y, 19) = md (x-1, y,   20)
md (x, y, 20) = md (x,   y+1, 19)

-- Cycle 4 (y ↦ 2y+1)
md (x, y, 21) = md (x+1, y,   22)
md (x, y, 22) = md (x+1, y,   23)
md (x, y, 23) = md (x,   y-1, 21)
md (x, y, 24) = md (x-1, y,   25)
md (x, y, 25) = md (x,   y+1, 24)

-- Drain (y → 0)
md (x, y, 26) = md (x,   y-1, 26)
